# Generated by Django 4.2.16 on 2026-05-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscoNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_id', models.CharField(default='', max_length=128)),
                ('role', models.CharField(default='GROUP_NODE', max_length=32)),
                ('group_id', models.IntegerField(default=1)),
                ('chain_id', models.IntegerField(default=1)),
                ('p2p_port', models.IntegerField(default=30300)),
                ('channel_port', models.IntegerField(default=20200)),
                ('jsonrpc_port', models.IntegerField(default=8545)),
                ('status', models.CharField(default='CREATED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
